FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
# Każdy kontener uruchamia swoją instancję FastAPI lub Workera
CMD ["uvicorn", "crm_service.main:app", "--host", "0.0.0.0", "--port", "8004"]